### ISSUE TITLE
Copy "Authorization:" Header over to `X-Authorization` before contacting Jolokia

### ISSUE THREAD

**Issue by rhuss** [hawtio/hawtio-oauth#11]
On OpenShift this would allow Jolokia accessed through the OpenShift proxy to validate the token, too. OpenShift itself filters the original `Authorization:` 

I hope this is the proper project for this Issue.

**Comment by gashcrumb** [comment]
@rhuss Oh right, I actually did that here -> https://github.com/hawtio/hawtio-jmx/commit/67997dfd5a3f207307afb56b794f8a8f17365800 though it's specifically done when jolokia's being used.

**Comment by rhuss** [comment]
That's perfectly fine, thanks ;-)
