### ISSUE TITLE
Add support for github oauth flow

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-oauth#15]
@jstrachan fyi...

**Comment by gashcrumb** [comment]
https://developer.github.com/v3/oauth/

**Comment by gashcrumb** [comment]
Hey, I did this!  Starting here -> https://github.com/hawtio/hawtio-oauth/commit/35951cd4b7479a037d477f4ae2ec88c31e1d7c46

**Comment by jstrachan** [comment]
ooh!

**Comment by gashcrumb** [comment]
There's just the issue of providing the keys to the console somehow :-)
